# Generated by Django 3.0.8 on 2020-08-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('Quartier', 'Quartier'), ('Eglise', 'Eglise'), ('Cathédrale', 'Cathédrale')], max_length=20)),
                ('nom', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=120)),
                ('historique', models.TextField()),
                ('remarque', models.CharField(blank=True, max_length=120, null=True)),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ville.Noms')),
            ],
        ),
    ]
