# Generated by Django 3.0.2 on 2020-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ville', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noms',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noms',
            name='verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='noms',
            name='selection',
            field=models.CharField(choices=[('Eglise', 'Eglise'), ('Cathédrale', 'Cathédrale'), ('Fermes-Châteaux', 'Fermes-Châteaux'), ('Maisons', 'Maisons'), ('Greniers', 'Greniers'), ('Musées', 'Musées'), ('Ponts', 'Ponts'), ('Plans de la ville', 'Plans'), ('Remparts - Fortifications', 'Remparts-Fortifications'), ('Hôtels particuliers', 'Hôtels_particuliers')], max_length=25),
        ),
        migrations.AlterField(
            model_name='noms',
            name='slug',
            field=models.SlugField(),
        ),
    ]
