# Generated by Django 3.0.2 on 2020-08-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ville', '0003_auto_20200829_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noms',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
